#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="0.4.4"
URL="http://downloads.sourceforge.net/project/phpmumbleadmin/phpMumbleAdmin-${VERSION}.zip"
MM_URL="https://github.com/dieonar/MyMumb-Panel/archive/master.zip"

dl $URL /usr/local/src
dl $MM_URL /usr/local/src
