#!/bin/bash -ex

SRC=/usr/local/src
WEBROOT=/var/www

a2enmod rewrite

a2dissite 000-default.conf
a2ensite tkl-webcp.conf

mv /var/www/js /var/www/tkl-webcp
mv /var/www/css /var/www/tkl-webcp
mkdir /var/www/tkl-webcp/images
mv /var/www/images/* /var/www/tkl-webcp/images
rm -rf /var/www/images

#Adding additional information about preconfigured ports (temporary) until workaround.
sed -i 's/^\(registerName=\)/\1TurnKey Mumble Server/g' /etc/mumble-server.ini

phpenmod IcePHP
echo 'include_path=/usr/share/php/Ice' >> /etc/php/7.0/apache2/conf.d/20-IcePHP.ini

systemctl enable murmurdautofirewall || update-rc.d murmurdautofirewall defaults

